### ISSUE TITLE
Issue new release of Zero asap

### ISSUE THREAD

**Issue by jilljenn** [mangaki/zero#39]

**Comment by RaitoBezarius** [comment]
Pourquoi ?

**Comment by jilljenn** [comment]
Asap j'ai dit
Parce que SVD release n'est pas SVD master or Mangaki a besoin de SVD master donc actuellement je pip install git+etc.

**Comment by jilljenn** [comment]
(j'ai écrit "Asap j'ai dit" avant de savoir que tu avais répondu)

**Comment by jilljenn** [comment]
Ce serait cool d'automatiser le déploiement vers PyPI (pas prioritaire)

**Comment by RaitoBezarius** [comment]
Il est automatisé pourtant ?

**Comment by RaitoBezarius** [comment]
https://github.com/mangaki/zero/actions/runs/3088252463
